# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 50, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cipher = QtWidgets.QTextBrowser(self.centralwidget)
        self.btn_cipher.setGeometry(QtCore.QRect(120, 270, 331, 101))
        self.btn_cipher.setObjectName("btn_cipher")
        self.btn_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.btn_info.setGeometry(QtCore.QRect(640, 140, 331, 101))
        self.btn_info.setObjectName("btn_info")
        self.btn_sign = QtWidgets.QTextBrowser(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(640, 270, 331, 101))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_plain = QtWidgets.QTextBrowser(self.centralwidget)
        self.btn_plain.setGeometry(QtCore.QRect(120, 140, 331, 101))
        self.btn_plain.setObjectName("btn_plain")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 320, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 170, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(530, 310, 91, 16))
        self.label_5.setObjectName("label_5")
        self.en_click = QtWidgets.QPushButton(self.centralwidget)
        self.en_click.setGeometry(QtCore.QRect(160, 410, 93, 28))
        self.en_click.setObjectName("en_click")
        self.de_click = QtWidgets.QPushButton(self.centralwidget)
        self.de_click.setGeometry(QtCore.QRect(300, 410, 93, 28))
        self.de_click.setObjectName("de_click")
        self.sign_click = QtWidgets.QPushButton(self.centralwidget)
        self.sign_click.setGeometry(QtCore.QRect(680, 400, 93, 28))
        self.sign_click.setObjectName("sign_click")
        self.verify_click = QtWidgets.QPushButton(self.centralwidget)
        self.verify_click.setGeometry(QtCore.QRect(840, 400, 93, 28))
        self.verify_click.setObjectName("verify_click")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.label_4.setText(_translate("MainWindow", "Infomation"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.en_click.setText(_translate("MainWindow", "Encrypt"))
        self.de_click.setText(_translate("MainWindow", "Decrypt"))
        self.sign_click.setText(_translate("MainWindow", "Sign"))
        self.verify_click.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
